### PR TITLE
Link subprojects statically.

### PR DESCRIPTION
**Pull request by Kubiisek**
All subprojects are now linked statically. Only notable problem was with stb_image as there were two implementations, one in OvWindowing and the other one in OvRendering. I removed the one in OvWindowing. It'd nice if we created a function in OvTools to load images. `API/Export.h(s)` were deleted.

Subprojects set `$(PublicIncludeDirectories)` to `$(ProjectDir)include;$(PublicIncludeDirectories)` so that other projects that reference them add it to the their include path. If `Link Library Dependencies` is set to `true` then referenced projects are linked automatically. This option can be found in the Properties of the reference.
image

I'd like to also mention that library wrappers OvWindowing, OvPhysics and OvAudio include their external libraries in public headers included by other projects. I think that is undesirable as projects using those wrappers have to also add those external libraries to their include directories.

### CODE REVIEW

**Comment by adriengivry** [comment]
I've cloned and build the solution in debug (Because release builds are currently failing: https://github.com/adriengivry/Overload/issues/185).

Include files aren't found (Non-exhaustive log):
```
12>C:\Users\adrie\Desktop\Overload-Kubi\Sources\Overload\OvEditor\include\OvEditor\Panels\Hierarchy.h(9,10): fatal error C1083: Cannot open include file: 'OvRendering/Resources/Loaders/TextureLoader.h': No such file or directory
12>Inspector.cpp
12>C:\Users\adrie\Desktop\Overload-Kubi\Sources\Overload\OvEditor\include\OvEditor\Panels\Inspector.h(9,10): fatal error C1083: Cannot open include file: 'OvRendering/Resources/Loaders/TextureLoader.h': No such file or directory
12>MaterialEditor.cpp
12>C:\Users\adrie\Desktop\Overload-Kubi\Sources\Overload\OvEditor\include\OvEditor\Panels\MaterialEditor.h(9,10): fatal error C1083: Cannot open include file: 'OvUI/Widgets/Texts/Text.h': No such file or directory
12>MenuBar.cpp
12>C:\Users\adrie\Desktop\Overload-Kubi\Sources\Overload\OvEditor\src\OvEditor\Panels\MenuBar.cpp(7,10): fatal error C1083: Cannot open include file: 'OvTools/Utils/SystemCalls.h': No such file or directory
12>Profiler.cpp
12>C:\Users\adrie\Desktop\Overload-Kubi\Sources\Overload\OvEditor\include\OvEditor\Panels\Profiler.h(9,10): fatal error C1083: Cannot open include file: 'OvAnalytics/Profiling/Profiler.h': No such file or directory
12>ProjectSettings.cpp
12>C:\Users\adrie\Desktop\Overload-Kubi\Sources\Overload\OvEditor\include\OvEditor\Panels\ProjectSettings.h(7,10): fatal error C1083: Cannot open include file: 'OvUI/Widgets/Texts/Text.h': No such file or directory
12>SceneView.cpp
12>C:\Users\adrie\Desktop\Overload-Kubi\Sources\Overload\OvEditor\src\OvEditor\Panels\SceneView.cpp(7,10): fatal error C1083: Cannot open include file: 'OvUI/Plugins/DDTarget.h': No such file or directory
12>Toolbar.cpp
12>C:\Users\adrie\Desktop\Overload-Kubi\Sources\Overload\OvEditor\src\OvEditor\Panels\Toolbar.cpp(7,10): fatal error C1083: Cannot open include file: 'OvUI/Widgets/Layout/Spacing.h': No such file or directory
12>RawShaders.cpp
12>EditorSettings.cpp
12>C:\Users\adrie\Desktop\Overload-Kubi\Sources\Overload\OvEditor\include\OvEditor\Settings\EditorSettings.h(9,10): fatal error C1083: Cannot open include file: 'OvTools/Eventing/Event.h': No such file or directory
12>ActorCreationMenu.cpp
12>C:\Users\adrie\Desktop\Overload-Kubi\Sources\Overload\OvEditor\src\OvEditor\Utils\ActorCreationMenu.cpp(7,10): fatal error C1083: Cannot open include file: 'OvUI/Widgets/Menu/MenuList.h': No such file or directory
12>Generating Code...
12>Done building project "OvEditor.vcxproj" -- FAILED.
========== Build: 3 succeeded, 9 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by litelawliet** [comment]
I didn't have any trouble compiling this PR (https://github.com/adriengivry/Overload/pull/186#issuecomment-735439169) but we should try to confirm if the errors @adriengivry had are reproducible.

Also it turns out compiling with static linking instead of the dynamic one (dll) as before fix this issue : https://github.com/adriengivry/Overload/issues/185
We should now be able to compile in Release mode without re-definition errors.

**Comment by adriengivry** [comment]
Still doesn't work on my side. I've recloned the branch, hit "Build All" and same errors

**Comment by adriengivry** [comment]
After some investigation with @litelawliet, we found out that `PublicIncludeDirectories` aren't supported with older versions of Visual Studio, thus, includes won't work (Doesn't work with Visual Studio Version 16.7.5).
To ensure retro-compatibility, we should stick to the good old way

image

**Review by adriengivry — CHANGES_REQUESTED** [review]
See https://github.com/adriengivry/Overload/pull/186#issuecomment-736146762

**Comment by adriengivry** [comment]
I'm closing the PR as the plan to move to premake will solve this issue
